# SPDX-License-Identifier: MIT
"""GGA component — ports internal/components/gga/.

Config, install, runtime file management.
"""

from __future__ import annotations

import os
import shutil
from dataclasses import dataclass

from dxrk.components import filemerge
from dxrk.components.assets import read as assets_read
from dxrk.models import AgentID
from dxrk.system import PlatformProfile


@dataclass
class InjectionResult:
    ConfigFile: str = ""
    AgentsFile: str = ""
    ConfigChanged: bool = False
    AgentsChanged: bool = False

    def files_written(self) -> list[str]:
        files: list[str] = []
        if self.ConfigFile:
            files.append(self.ConfigFile)
        if self.AgentsFile:
            files.append(self.AgentsFile)
        return files


def post_install_messages() -> list[str]:
    return [
        "Ejecuta `DXRK_GUARDIAN install` en cualquier proyecto git para configurar el hook pre-commit",
        "Copia `~/.config/DXRK_GUARDIAN/AGENTS.md` a la raíz de tu proyecto y personalízalo",
    ]


def provider_for_agents(agent_ids: list[AgentID]) -> str:
    has = set(agent_ids)
    if AgentID.CLAUDE_CODE in has:
        return "claude"
    if AgentID.OPENCODE in has:
        return "opencode"
    if AgentID.GEMINI_CLI in has:
        return "gemini"
    if AgentID.ANTIGRAVITY in has:
        return "gemini"
    if AgentID.CODEX in has:
        return "codex"
    return "claude"


def build_config(provider: str) -> bytes:
    lines = [
        "# Dxrk Guardian Angel Configuration",
        "# Generated by dxrk",
        "",
        "# AI Provider for code review",
        "# Options: claude, gemini, codex, opencode, ollama:<model>",
        f"PROVIDER={provider!r}",
        "",
        "# File patterns to review (comma-separated globs)",
        'FILE_PATTERNS="*.ts,*.tsx,*.js,*.jsx,*.py,*.go"',
        "",
        "# Patterns to exclude",
        'EXCLUDE_PATTERNS="*.test.*,*.spec.*,*.d.ts,dist/*,build/*,node_modules/*"',
        "",
        "# Rules file",
        'RULES_FILE="AGENTS.md"',
        "",
        "# Strict mode (fail on ambiguous AI responses)",
        'STRICT_MODE="true"',
        "",
        "# Review timeout in seconds",
        'TIMEOUT="300"',
        "",
    ]
    return ("\n".join(lines)).encode("utf-8")


def config_path(home_dir: str) -> str:
    return os.path.join(home_dir, ".config", "DXRK_GUARDIAN", "config")


def agents_template_path(home_dir: str) -> str:
    return os.path.join(home_dir, ".config", "DXRK_GUARDIAN", "AGENTS.md")


def inject(home_dir: str, agent_ids: list[AgentID]) -> InjectionResult:
    provider = provider_for_agents(agent_ids)
    config_content = build_config(provider)
    cpath = config_path(home_dir)
    config_result = filemerge.write_file_atomic(cpath, config_content, 0o644)

    agents_content = assets_read("gga/AGENTS.md") or ""
    apath = agents_template_path(home_dir)
    agents_result = filemerge.write_file_atomic(apath, agents_content.encode("utf-8"), 0o644)

    ensure_dxrk_guardian_shim(home_dir)

    return InjectionResult(
        ConfigFile=cpath,
        AgentsFile=apath,
        ConfigChanged=config_result.Changed,
        AgentsChanged=agents_result.Changed,
    )


def ensure_dxrk_guardian_shim(home_dir: str) -> None:
    """Bridge the upstream `gga` binary to the `DXRK_GUARDIAN` name.

    Upstream (Gentleman-Programming/gentleman-guardian-angel) installs `gga`
    reading `~/.config/gga/config`, while Dxrk hooks invoke `DXRK_GUARDIAN`
    with `~/.config/DXRK_GUARDIAN/config`. Link both names — but only when the
    legacy paths do not exist yet, never overwriting user files. No-op when
    `gga` is absent.
    """
    gga_bin = shutil.which("gga")
    if gga_bin is None:
        return
    bin_dir = os.path.join(home_dir, ".local", "bin")
    link = os.path.join(bin_dir, "DXRK_GUARDIAN")
    try:
        if not os.path.lexists(link):
            os.makedirs(bin_dir, exist_ok=True)
            os.symlink(gga_bin, link)
    except OSError:
        pass
    gga_cfg = os.path.join(home_dir, ".config", "gga")
    dxrk_cfg = os.path.join(home_dir, ".config", "DXRK_GUARDIAN")
    try:
        if not os.path.lexists(gga_cfg) and os.path.isdir(dxrk_cfg):
            os.symlink(dxrk_cfg, gga_cfg)
    except OSError:
        pass


def install_command(profile: PlatformProfile) -> list[list[str]]:
    from dxrk.models import ComponentID
    from dxrk.pipeline import resolve_component_install

    return resolve_component_install(profile, ComponentID.DXRK_GUARDIAN)


def should_install(enabled: bool) -> bool:
    return enabled


# ─── Runtime ───────────────────────────────────────────────────────────────


def runtime_lib_dir(home_dir: str) -> str:
    return os.path.join(home_dir, ".local", "share", "DXRK_GUARDIAN", "lib")


def runtime_bin_dir(home_dir: str) -> str:
    return os.path.join(home_dir, ".local", "share", "DXRK_GUARDIAN", "bin")


def runtime_pr_mode_path(home_dir: str) -> str:
    return os.path.join(runtime_lib_dir(home_dir), "pr_mode.sh")


def runtime_ps1_path(home_dir: str) -> str:
    return os.path.join(home_dir, "bin", "DXRK_GUARDIAN.ps1")


def ensure_runtime_assets(home_dir: str) -> None:
    pr_mode_path = runtime_pr_mode_path(home_dir)
    content = assets_read("gga/pr_mode.sh")
    if content is None:
        raise FileNotFoundError("activo de runtime gga integrado pr_mode.sh no encontrado")
    filemerge.write_file_atomic(pr_mode_path, content.encode("utf-8"), 0o755)


def ensure_powershell_shim(home_dir: str) -> None:
    ps1_path = runtime_ps1_path(home_dir)
    content = assets_read("gga/gga.ps1")
    if content is None:
        raise FileNotFoundError("activo de runtime gga integrado gga.ps1 no encontrado")
    filemerge.write_file_atomic(ps1_path, content.encode("utf-8"), 0o755)
